# Tensor Basics

In [36]:
"""import module"""
import torch
import numpy as np

In [2]:
"""empty 1D tensor with 3 elements"""
x = torch.empty(3)
print(x)

tensor([ 0.0000e+00,  2.5244e-29, -1.8275e-33])


In [3]:
"""empty 2D tensor """
x = torch.empty(2,3)
print(x)

tensor([[3.6742e-42, 0.0000e+00, 9.7566e-37],
        [1.0050e-36, 0.0000e+00, 2.5244e-29]])


In [4]:
"""empty 3D tensor """
x = torch.empty(2,3,3)
print(x)

tensor([[[7.4630e-33, 1.4013e-45, 6.8361e-34],
         [1.4013e-45, 7.0731e-34, 1.4013e-45],
         [7.0716e-34, 1.4013e-45, 1.0641e-33]],

        [[1.4013e-45, 6.9840e-34, 1.4013e-45],
         [7.4133e-33, 1.4013e-45, 6.8659e-34],
         [1.4013e-45, 6.7085e-33, 1.4013e-45]]])


**Note:** Dimensions can be more in tensor, based on our tasks.

In [5]:
"""tensor with random values"""
x = torch.rand(2,3)
print(x)

tensor([[0.0273, 0.1154, 0.5889],
        [0.5341, 0.1374, 0.3637]])


In [6]:
"""zeros tensors"""
x = torch.zeros(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
"""ones tensor """
x = torch.ones(2,3)
print(x)

print("\nThe data type is: ",x.dtype) #data type by default

tensor([[1., 1., 1.],
        [1., 1., 1.]])

The data type is:  torch.float32


**Note:** default data type is torch.float32

In [8]:
"""different data types"""
x = torch.ones(2,2, dtype = torch.int)
print(x)
print("The data type is: ",x.dtype, "\n")

x = torch.ones(2,2, dtype = torch.float64)
print(x)
print("The data type is: ",x.dtype, "\n")

x = torch.ones(2,2, dtype = torch.double)
print(x)
print("The data type is: ",x.dtype, "\n")

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)
The data type is:  torch.int32 

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)
The data type is:  torch.float64 

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)
The data type is:  torch.float64 



In [9]:
"""looking at the shape"""
x = torch.ones(2,3)
print(x)

print("\nThe shape is: ",x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.]])

The shape is:  torch.Size([2, 3])


In [10]:
"""from list to tensor"""
list_1 = [2.5, 1.4]
x = torch.tensor(list_1)
print(x)

tensor([2.5000, 1.4000])


## Basic Operations

In [11]:
"""creating two random tensors"""
x = torch.rand(2,2)
y = torch.rand(2,2)

print("x is:\n",x)
print("y is:\n",y)

x is:
 tensor([[0.1367, 0.1308],
        [0.7800, 0.1748]])
y is:
 tensor([[0.4870, 0.5225],
        [0.4195, 0.6217]])


In [12]:
"""elementwise addition of tensors"""
z = x+y
print("z is:\n",z)

z is:
 tensor([[0.6238, 0.6533],
        [1.1994, 0.7965]])


In [13]:
"""using functions"""
z = torch.add(x,y)
print("z is:\n",z)

z is:
 tensor([[0.6238, 0.6533],
        [1.1994, 0.7965]])


In [14]:
"""add by using inplace operator"""
c = y.add_(x) #this can directly modefy y
print("c is:\n",c)

c is:
 tensor([[0.6238, 0.6533],
        [1.1994, 0.7965]])


In [15]:
"""elementwise subtractions"""
z = x-y
print("z is:\n",z)

z = torch.sub(x,y)
print("z is:\n",z)

z is:
 tensor([[-0.4870, -0.5225],
        [-0.4195, -0.6217]])
z is:
 tensor([[-0.4870, -0.5225],
        [-0.4195, -0.6217]])


In [16]:
"""substract by using inplace operator"""
c = y.sub_(x) #this can directly modefy y
print("c is:\n",c)

c is:
 tensor([[0.4870, 0.5225],
        [0.4195, 0.6217]])


In [17]:
"""elementwise multiplications"""
z = x*y
print("z is:\n",z)

z = torch.mul(x,y)
print("z is:\n",z)

z is:
 tensor([[0.0666, 0.0683],
        [0.3272, 0.1087]])
z is:
 tensor([[0.0666, 0.0683],
        [0.3272, 0.1087]])


In [18]:
"""multiplications by using inplace operator"""
c = y.mul_(x) #this can directly modefy y
print("c is:\n",c)

c is:
 tensor([[0.0666, 0.0683],
        [0.3272, 0.1087]])


In [19]:
"""elementwise divisions"""
z = x/y
print("z is:\n",z)

z = torch.div(x,y)
print("z is:\n",z)

z is:
 tensor([[2.0534, 1.9138],
        [2.3840, 1.6085]])
z is:
 tensor([[2.0534, 1.9138],
        [2.3840, 1.6085]])


In [20]:
"""divisions by using inplace operator"""
c = y.div_(x) #this can directly modefy y
print("c is:\n",c)

c is:
 tensor([[0.4870, 0.5225],
        [0.4195, 0.6217]])


## Slice Tensor

In [32]:
"""tensor sliceing"""
x = torch.rand(5,3)
print("x is:\n",x) #full tensor
print("\nfull first column:\n",x[:,0])
print("\nfull first row:\n",x[0,:])
print("\nfull second column:\n",x[:,1])
print("\nfull second row:\n",x[1,:])
print("\nspecific element from fixed position:\n",x[1,1]) #return tensor with one element

x is:
 tensor([[0.1673, 0.5566, 0.8198],
        [0.7701, 0.1661, 0.8031],
        [0.8131, 0.0846, 0.7953],
        [0.5234, 0.4021, 0.6992],
        [0.1767, 0.2628, 0.1428]])

full first column:
 tensor([0.1673, 0.7701, 0.8131, 0.5234, 0.1767])

full first row:
 tensor([0.1673, 0.5566, 0.8198])

full second column:
 tensor([0.5566, 0.1661, 0.0846, 0.4021, 0.2628])

full second row:
 tensor([0.7701, 0.1661, 0.8031])

specific element position:
 tensor(0.1661)


**Note:** if we have only one value in a tensor then we can get an actual value, such as, 

In [33]:
print("\nspecific element from fixed position:\n",x[1,1]) #return tensor with one element
print("\nactual value:\n",x[1,1].item()) #print the actual value


specific element from fixed position:
 tensor(0.1661)

actual value:
 0.1660732626914978


In [35]:
"""reshaping a tensor"""
x = torch.rand(4,4)
print("\nx is:\n",x)

v = x.view(16) # 4*4 = 16, makes it one dimensional tensor
print("\nv is:\n",v)
print("shape of v:\n",v.size())

w = x.view(-1, 8) # PyTorch automatically determine the dimensions of the tensor by 8
print("\nv is:\n",w)
print("shape of v:\n",w.size())


x is:
 tensor([[0.7174, 0.7981, 0.1795, 0.0218],
        [0.5247, 0.3388, 0.9068, 0.4909],
        [0.3043, 0.4821, 0.8294, 0.9601],
        [0.1377, 0.4732, 0.0550, 0.1595]])

v is:
 tensor([0.7174, 0.7981, 0.1795, 0.0218, 0.5247, 0.3388, 0.9068, 0.4909, 0.3043,
        0.4821, 0.8294, 0.9601, 0.1377, 0.4732, 0.0550, 0.1595])
shape of v:
 torch.Size([16])

v is:
 tensor([[0.7174, 0.7981, 0.1795, 0.0218, 0.5247, 0.3388, 0.9068, 0.4909],
        [0.3043, 0.4821, 0.8294, 0.9601, 0.1377, 0.4732, 0.0550, 0.1595]])
shape of v:
 torch.Size([2, 8])


## Numpy to Torch Tensor
   - If we create tensor from numpy array, they both share the same memory location. If we change one, then the other one automatically change.

In [46]:
"""tensor to numpy array"""
a = torch.ones(5)
print("a is:\n",a, "\nand the type: ",type(a))
b = a.numpy()
print("\nb is:\n",b, "\nand the type: ",type(b))

print("\nchanage one automatically change other one:")
"""chanage one automatically change other one"""
a.add_(1) #using inplace addition

print("\na is:\n",a, "\nand the type: ",type(a))
print("\nb is:\n",b, "\nand the type: ",type(b))

a is:
 tensor([1., 1., 1., 1., 1.]) 
and the type:  <class 'torch.Tensor'>

b is:
 [1. 1. 1. 1. 1.] 
and the type:  <class 'numpy.ndarray'>

chanage one automatically change other one:

a is:
 tensor([2., 2., 2., 2., 2.]) 
and the type:  <class 'torch.Tensor'>

b is:
 [2. 2. 2. 2. 2.] 
and the type:  <class 'numpy.ndarray'>


In [47]:
"""numpy array to tensor"""
a = np.ones(5)
print("a is:\n",a, "\nand the type: ",type(a))
b = torch.from_numpy(a)
print("\nb is:\n",b, "\nand the type: ",type(b))

print("\nchanage one automatically change other one:")
"""chanage one automatically change other one"""
a += 1 # increment by one

print("\na is:\n",a, "\nand the type: ",type(a))
print("\nb is:\n",b, "\nand the type: ",type(b))

a is:
 [1. 1. 1. 1. 1.] 
and the type:  <class 'numpy.ndarray'>

b is:
 tensor([1., 1., 1., 1., 1.], dtype=torch.float64) 
and the type:  <class 'torch.Tensor'>

chanage one automatically change other one:

a is:
 [2. 2. 2. 2. 2.] 
and the type:  <class 'numpy.ndarray'>

b is:
 tensor([2., 2., 2., 2., 2.], dtype=torch.float64) 
and the type:  <class 'torch.Tensor'>


**Note:** data type by default float64, we can fix it if we want.

**Note:** numpy can only handle CPU tensor, GPU tensor can't be handle by numpy operator. 

In [49]:
"""creating torch tensor using GPU"""

if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device = device) # device assign directly, gpu tensor
    y = torch.ones(5)
    y = y.to(device) # shifting cpu tensor to gpu
    z = x+y # gpu tensor, can't be modefied by numpy
    z = z.to("cpu") # convert to cpu tensor, can be modefied by numpy
else:
    print("GPU is not available!")
    

GPU is not available!


In [50]:
"""if gradient need to be calculated"""
x = torch.ones(5, requires_grad = True)
print("x is:\n",x)

x is:
 tensor([1., 1., 1., 1., 1.], requires_grad=True)
